### ISSUE TITLE
iscoroutine returns false when given CoroutineMock

### ISSUE THREAD

**Issue by pzelnip** [Martiusweb/asynctest#101]
Asyncio's ```iscoroutine()``` method returns false when given a ```CoroutineMock```:

```
>>> asyncio.iscoroutine(asynctest.CoroutineMock())
False
```

This means that if you're testing code where your CoroutineMock is passed to ```call_soon_threadsafe``` then it blows up with a TypeError:

```
    asyncio.run_coroutine_threadsafe(self.recv_queue.put(data), self.loop)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

coro = <MagicMock name='mock.put()' id='4571939168'>, loop = <_UnixSelectorEventLoop running=False closed=False debug=False>

    def run_coroutine_threadsafe(coro, loop):
        """Submit a coroutine object to a given event loop.

        Return a concurrent.futures.Future to access the result.
        """
        if not coroutines.iscoroutine(coro):
>           raise TypeError('A coroutine object is required')
E           TypeError: A coroutine object is required
```

You can workaround this by giving a spec argument to the CoroutineMock, but ideally a CoroutineMock should be able to be used where any coroutine can be used (isn't that the purpose of a CoroutineMock?)

**Comment by Martiusweb** [comment]
Hi,

CoroutineMock is actually mocking a coroutine function, thus, the coroutine is the result of a call to the instance of CoroutineMock

>>> import asyncio, asynctest
>>> asyncio.iscoroutine(asynctest.CoroutineMock())
False
>>> asyncio.iscoroutinefunction(asynctest.CoroutineMock())
True
>>> asyncio.iscoroutine(asynctest.CoroutineMock()())
True
>>> asyncio.iscoroutinefunction(asynctest.CoroutineMock()())
False

This is a common confusion, I opened a new issue to rename the class.
