### ISSUE TITLE
Calling mock_add_spec on a mock created with create_autospec results in an error

### ISSUE THREAD

**Issue by Wesmania** [Martiusweb/asynctest#107]
Demonstrated by the following session for asynctest 0.12.2:

```
>>> import asynctest
>>> o = object()
>>> am = asynctest.create_autospec(o)
>>> am.mock_add_spec(["c"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/dane/common-home/Pobrane/faf/replayserver-venv/lib/python3.6/site-packages/asynctest/mock.py", line 244, in mock_add_spec
    self._mock_set_async_magics()
  File "/mnt/dane/common-home/Pobrane/faf/replayserver-venv/lib/python3.6/site-packages/asynctest/mock.py", line 233, in _mock_set_async_magics
    delattr(self, entry)
  File "/usr/lib64/python3.6/unittest/mock.py", line 728, in __delattr__
    raise AttributeError(name)
AttributeError: __aiter__
```

Occasionally `AttributeError: __aexit__` is thrown in the same place instead. Equivalent unittest.mock session:

```
>>> from unittest import mock
>>> o = object()
>>> m = mock.create_autospec(o)
>>> m.mock_add_spec(["c"])
>>> m.c
<MagicMock name='mock.c' id='139969003892632'>
```

**Comment by Wesmania** [comment]
Quick pdb session shows that the attributes are defined in `self._mock_children`. I'm not familiar with mock internals, it's probably used for autospec to work? The value of self._mock_children is:
`{'__aexit__': sentinel.DELETED, '__aenter__': sentinel.DELETED, '__anext__': sentinel.DELETED, '__aiter__': sentinel.DELETED}`
I guess that we should either catch the `AttributeError` and proceed as normal or check `self._mock_children` ourselves. The earlier option sounds more reasonable to me.

**Comment by Kentzo** [comment]
What is the behavior of unittest.Mock?

**Comment by Wesmania** [comment]
I listed it in the original comment.

**Comment by Martiusweb** [comment]
Thanks for the report, I'll try to look at it today or tomorrow.

**Comment by Wesmania** [comment]
Bump, still happens on 0.12.3, I'd love to be able to run the few tests I have that use this on travis instead of just locally :)

**Comment by Martiusweb** [comment]
Sorry for the long delay, the bug is fixed and merged.
I prepared a new release (0.12.4) that will be processed by the CI soon.
