### ISSUE TITLE
Coroutine not patched correctly after using MagicMock as constructor

### ISSUE THREAD

**Issue by z0u** [Martiusweb/asynctest#113]
When mocking a class and using it in place of a constructor, async methods in the resulting mocked object are not coroutines:

```python
>>> import asynctest
>>> class AsyncStub:
...     async def do_async(self):
...         await True
... 
>>> type(asynctest.MagicMock(AsyncStub)().do_async)
<class 'asynctest.mock.MagicMock'>
>>> type(asynctest.MagicMock(AsyncStub()).do_async)
<class 'asynctest.mock.CoroutineMock'>
```

I expected that in the first case, `do_async` should be a `CoroutineMock`.

**Comment by Martiusweb** [comment]
Hi,

This is because asynctest follows the behavior of unittest, which makes no difference between a constructor and a regular function call:

    import unittest.mock

    class Foo:
        def bar(self):
            pass

    isinstance(FooMock(), Foo)  # False, because FooMock() returns a "regular" mock
    hasattr(FooMock, 'bar')     # True, because bar is an attribute of class Foo (its spec)
    hasattr(FooMock(), 'bar')   # True, because a this mock has no spec attached
    hasattr(FooMock, 'baz')     # False, because baz isn't an attribue of class Foo (its spec)
    hasattr(FooMock(), 'baz')   # True, because, again, this mock as no spec, even
                                # if it seems to be the result of the constructor

Asynctest is designed to extend the behavior of unittest, but don't change it.

You need to specify the result of the call to the constructor:

    AsyncStubMock = asynctest.mock.MagicMock(AsyncStub, side_effect=lambda *a, **kw: asynctest.mock.MagicMock(AsyncStub))

Maybe adding helpers like mock_class() and @patch_class() that do the above would be a good idea.

**Comment by Martiusweb** [comment]
In fact, I forgot that ``create_autospec()``< solves this exact problem:

    AsyncStubMock = create_autospec(AsyncStub)  # will correctly mock the constructor
    AsyncStubMock().do_async # is a CoroutineMock

I updated the documentation because it was missing.
