### ISSUE TITLE
patch.dict() does not resolve string references on Python 3.7.3

### ISSUE THREAD

**Issue by agronholm** [Martiusweb/asynctest#115]
There was a change made to `patch.dict()` which breaks the corresponding feature in `asynctest.mock`: https://bugs.python.org/issue35512

Attempting to use it will give an error like this:

```
/usr/local/lib/python3.7/site-packages/asynctest/mock.py:1240: in _patch_dict
    self._original = self.in_dict.copy()
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by Martiusweb** [comment]
The fix has been merged, it will be part of the release 0.12.3 (it's in the CI pipeline).

Thanks for the report.
