### ISSUE TITLE
 Builds for Python 3.4 on MacOS are broken

### ISSUE THREAD

**Issue by Martiusweb** [Martiusweb/asynctest#118]
Asynctest can't be tested on MacOS with Python 3.4 anymore on travis.

    ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

I suspect that the version of openssl installed by brew is too recent to be compatible with Python 3.4 (IIRC, some functions have been removed from openssl).

I'm not sure I want to spend time on this, so maybe I'll just deactivate this target.

**Comment by RemiCardona** [comment]
3.4 has been EOLed 3 weeks ago, I suggest dropping support for 3.4 entirely to avoid a maintenance headache.

https://www.python.org/dev/peps/pep-0429/

Cheers

**Comment by Martiusweb** [comment]
That's good news, it opens the discussion about removing old-style coroutines and eventually dropping their support in asynctest.

I opened a pull request, and will merge it before the next "major" release unless some concerns are expressed by users.
