### ISSUE TITLE
[question] TestCase inherits from unittest.case.TestCase vs unittest.TestCase

### ISSUE THREAD

**Issue by ixje** [Martiusweb/asynctest#124]
The `TestCase` class inherits from `unittest.case.TestCase`
https://github.com/Martiusweb/asynctest/blob/2068b222fa2461572abc64e6687e2bfe4642694e/asynctest/case.py#L119
 as opposed to the commonly used `unittest.TestCase`. This seems to break introspection and automated test discovery in my IDE (PyCharm). I've manually changed it to use `unittest.TestCase` and so far I've not encountered issues. 

This makes me wonder; why are we not inheriting from `unittest.TestCase` and what might I be breaking by doing so?

-edit
fwiw I'm on python 3.7.0

**Comment by Martiusweb** [comment]
The change has been released in 0.13.

**Comment by ixje** [comment]
Thanks!
