### ISSUE TITLE
__anext__ mocking

### ISSUE THREAD

**Issue by x0zzz** [Martiusweb/asynctest#131]
Hi, how should I mock `__anext__` method so it returns a list element with each iteration in an `async for` construct?
Here's a snippet of what I tried and failed at:

    from asyncio import get_event_loop
    from asynctest import create_autospec

    class A(object):
        def __aiter__(self):
            return self
    
        async def __anext__(self):
            print('A.__anext__()')
            raise StopAsyncIteration
    
    async def test(obj):
        async for cnt in obj:
            print(cnt)
    
    mock = create_autospec(A)
    mock.__anext__.side_effect = [4,5,6]
    
    get_event_loop().run_until_complete(test(A()))
    get_event_loop().run_until_complete(test(mock))
    print(mock.mock_calls)

When I run it I get:

    A.__anext__()
    [call.__aiter__()]

Seems that mock's `__anext__` method is never called.
What am I doing wrong here?

**Comment by tirkarthi** [comment]
I guess you should be mocking `__anext__.return_value` to return the required list of elements. Reference : https://asynctest.readthedocs.io/en/latest/tutorial.mocking.html#asynchronous-iterator .

```python
from asyncio import get_event_loop
from asynctest import create_autospec, MagicMock

class A:
    def __aiter__(self):
        return self

    async def __anext__(self):
        print('A.__anext__()')
        raise StopAsyncIteration

async def test(obj):
    async for cnt in obj:
        print(cnt)

mock = create_autospec(A)
mock.__aiter__.return_value = [4,5,6]

get_event_loop().run_until_complete(test(A()))
get_event_loop().run_until_complete(test(mock))
print(mock.mock_calls)
```

**Output**

```
A.__anext__()
4
5
6
[call.__aiter__()]
```

**Comment by x0zzz** [comment]
Awesome, thank you :)
