### ISSUE TITLE
Patching a more dififcult library like asyncpg?

### ISSUE THREAD

**Issue by fgimian** [Martiusweb/asynctest#141]
Hey there, absolutely love this library! 😄 

I'm really really struggling with something that should in theory be trivial.  I'm using the [asyncpg](https://github.com/MagicStack/asyncpg) library and am attempting to mock the `create_pool` function.

The strange thing about this library is that `connect_pool` is actually not defined as async, but it creates an instance of a class named `Pool` which has an `__await__` method which calls another method that's defined as async ... which then calls another .etc

So this seems to be the flow:

`create_pool` creates a `Pool` object:

```python
def create_pool(...)
    return Pool(...)
```

This has an `__await__` method:

```python
    def __await__(self):
        return self._async__init__().__await__()
```

That calls an async method which ultimatel calls another:

```python
    async def _async__init__(self):
    ...
            await self._initialize()
    ...
```

And that finally calls the connect async method from another class `PoolConnectionHolder`:

```
    async def _initialize(self):
        if self._minsize:
    ....
            first_ch = self._holders[-1]  # type: PoolConnectionHolder
            await first_ch.connect()
    ....
```

So this is a bit of a headache to comprehend, but ultimately, a basic mock of `create_pool` doesn't work:

```python
import asynctest
import asyncpg

with asynctest.patch("asyncpg.create_pool") as create_pool_mock:
    await asyncpg.create_pool()
```

The only way I've gotten it to work so far is patching the very bottom `connect` method like so:

```python
with asynctest.patch("asyncpg.pool.PoolConnectionHolder") as holder_mock:
    holder_mock.return_value.connect = asynctest.CoroutineMock(return_value="boo")
    await asyncpg.create_pool()
```

I'm continuing to try further ideas but ultimately, I want to mock the `create_pool` function and make it return a `MagicMock` `Pool` object so I can mock various methods in there.

I realise this is more of a question than a bug, but I wonder if anyone could maybe provide some suggestions on how to handle this as I'm really stuck?

Huge love and thanks
Fotis

**Comment by fgimian** [comment]
Here's a little codebase to make it easy to see the structure and reproduce:

```python
class PoolConnectionHolder:
    async def connect(self):
        print("Connecting")

class Pool:
    def __await__(self):
        return self._async__init__().__await__()

    async def _async__init__(self):
        await self._initialize()

    async def _initialize(self):
        first_ch = PoolConnectionHolder()
        await first_ch.connect()

def create_pool():
    return Pool()```

😄

**Comment by fgimian** [comment]
The solution posted by Zozz at https://stackoverflow.com/questions/32480108/mocking-async-call-in-python-3-5 allowed me to easily mock this.

Kindest regards
Fotis

**Comment by briggleman** [comment]
I wanted to say that in Python 3.8 this can be accomplished like so:

```python
@pytest.fixture(autouse=True)
def mocked_asyncpg(mock_records):
    def fetch(query, keys):
        records = None
        table = re.search(table_pattern, query).group(1)
        id = re.search(key_pattern, query).group(1)
        data = mock_records.get(table)
        records = [row for row in data for key in keys if row[id] == key]
        
        if records:
            return records
        return []

    with patch("circular_api.utils.database.create_pool", new_callable=AsyncMock) as mocked_pool:
        mocked = mocked_pool.return_value.acquire.return_value
        mocked.fetch.side_effect = fetch

        yield mocked
```
