### ISSUE TITLE
Specify multiple return values with list using CoroutineMock

### ISSUE THREAD

**Issue by elenaoat** [Martiusweb/asynctest#142]
Is there a way to specify multiple return values, as in case of MagicMock: 
`MagicMock(side_effect=[1, 2])`? This doesn't seem to work with CoroutineMock.

**Comment by elenaoat** [comment]
This seems to work with side_effect

**Comment by Martiusweb** [comment]
>>> import asyncio, asynctest
>>> magic = asynctest.MagicMock(return_value=[1, 2])
>>> magic()
[1, 2]
>>> coro = asynctest.CoroutineMock(return_value=[1, 2])
>>> asyncio.run(coro())
[1, 2]

This is the intended behavior.
