### ISSUE TITLE
conflict with sure project

### ISSUE THREAD

**Issue by hyzhak** [Martiusweb/asynctest#18]
Here is deep explanation https://github.com/gabrielfalcao/sure/issues/124. Because I sent few hours on chasing this bug I think It may help other developers too, before solution will be found.

**Comment by Martiusweb** [comment]
Hi, thanks for the report.

Unfortunately, I don't think I'll have time to look at it this week, nor if this is something I can really fix: for instance, this bug may be caused sure breaking builtins it doesn't know about, and maybe doesn't support python 3.5 yet (pure speculation).

I'll try to investigate if I can find an our or two.

**Comment by hyzhak** [comment]
@Martiusweb sad to hear but anyway keep me up to date. thanks for you support

**Comment by timofurrer** [comment]
I know, it's been a while but I've finally found time to dig into it. 

I've just pushed a bug fix: https://github.com/gabrielfalcao/sure/pull/128

We'll release soon.

**Comment by Martiusweb** [comment]
Thank you very much for your time and effort.

I close the issue.

**Comment by siyb** [comment]
@timofurrer: Thank you for fixing the issue, very much appreciated.
