### ISSUE TITLE
patch('aiohttp.ClientSession.get') fails to detect coroutine

### ISSUE THREAD

**Issue by rndusr** [Martiusweb/asynctest#23]
I'm trying to mock an aiohttp GET request, but asynctest uses MagicMock instead of CoroutineMock.

```python
import asynctest
import aiohttp
class TestAiohttp(asynctest.TestCase):
    @asynctest.patch('aiohttp.ClientSession.get')
    async def test_get_request(self, mock_get):
        response = aiohttp.ClientSession().get('http://localhost/')
        coro = response.text()
        self.assertEqual(type(coro), asynctest.CoroutineMock)
```

This test should pass, shouldn't it? I get:

```
AssertionError: <class 'asynctest.mock.MagicMock'> != <class 'asynctest.mock.CoroutineMock'>
```

I'm using the current master branch.

**Comment by Martiusweb** [comment]
Thanks for the report.

aiohttp.ClientSession.get returns an awaitable (instance of the coroutine
function _request), but it's not a coroutine (it's not prefixed by async or
decorated with @asyncio.coroutine). Unfortunately asynctest has no way to
detect when a function returns an awaitable and can't mock it as a
coroutine. You must deal with this case manually.

It seems that aiohttp is hard to mock (I also had issues with the async
context manager of ClientResponse for instance), in the case you describe,
there is not much asynctest can do...

**Comment by rndusr** [comment]
What a pitty. This is the first time I'm dipping my toe into mocking and it's
hard enough as it is.

But thanks for the quick reply!

**Comment by sashgorokhov** [comment]
Hope this piece of code written by me could help anyone: 

```python
def create_response(data):
    response = aiohttp.ClientResponse('get', URL('http://reddit.com/.json'))
    response.headers = {'Content-Type': 'application/json'}

    def side_effect(*args, **kwargs):
        fut = helpers.create_future(asyncio.get_event_loop())
        fut.set_result(json.dumps(data).encode())
        return fut

    content = response.content = mock.Mock()
    content.read.side_effect = side_effect

    return response


@contextlib.contextmanager
def mock_session(session, response):
    """
    :param aiohttp.ClientSession session:
    :param aiohttp.ClientResponse response:
    """
    request = session._request

    session.mock = mock.Mock()

    async def _request(*args, **kwargs):
        session.mock(*args, **kwargs)
        return response

    session._request = _request

    try:
        yield session
    finally:
        session._request = request
```

**Comment by pnuckowski** [comment]
I leave it here https://pypi.python.org/pypi/aioresponses to mock aiohttp ClientSession 

Maybe someone will find it useful :)
