### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_spec_coroutines'

### ISSUE THREAD

**Issue by siyb** [Martiusweb/asynctest#30]
**Version:**
0.9.0

**Test Code:**
    from asynctest import TestCase as AsyncTestCase
    from asynctest import CoroutineMock

    class WebsocketClientTest(AsyncTestCase):

        def test_foo(self):
            test = CoroutineMock()
            ...

  File "/MYPATH/venv/lib/python3.5/site-packages/asynctest/mock.py", line 86, in _mock_add_spec
    if asyncio.iscoroutinefunction(getattr(spec, attr)):
AttributeError: 'NoneType' object has no attribute '_spec_coroutines'

Am I doing something wrong here? I have tried specifying a side_effect and return_value, yields same error.

**Comment by siyb** [comment]
while checking the other tickets I found https://github.com/Martiusweb/asynctest/issues/18, seems to be this issue, ticket can be closed.

**Comment by Martiusweb** [comment]
Thanks to the report, I'll try to have a look at #18 again.
