### ISSUE TITLE
Implement create_autospec

### ISSUE THREAD

**Issue by smessmer** [Martiusweb/asynctest#37]
Sometimes, it isn't possible for me to create instances of mocked classes, because I don't have the dependencies. So I can't call

    mock = Mock(MyClass())

but I'd rather use

    mock = create_autospec(MyClass)

I didn't find this functionality in asynctest. Is this planned?

**Comment by ealfie** [comment]
On Wednesday, March 8, 2017, Sebastian Meßmer <notifications@github.com>
wrote:

> Sometimes, it isn't possible for me to create instances of mocked classes,
> because I don't have the dependencies. So I can't call
>
> mock = Mock(MyClass())
>
> but I'd rather use
>
> mock = create_autospec(MyClass)
>
> I didn't find this functionalitz in asynctest. Is this planned?
>
That would be great.

**Comment by Martiusweb** [comment]
Hi,

Thanks for the report.

I've never used create_autospec myself, the feature is not "planned" but I will look at how it can be implemented. Unfortunately I don't have much time to update asynctest at the moment so I can't give an ETA.

**Comment by Martiusweb** [comment]
relates to #46. Once ``create_autospec()`` is supported, ``patch()`` methods need to be overridden in order to support the ``autospec`` argument. It is also called in ``NonCallableMock.__getattr__()``.

**Comment by Martiusweb** [comment]
This is available in the PR/autospec branch.

Feedback is welcome!
