### ISSUE TITLE
assertRaises should support coroutines, futures or Task

### ISSUE THREAD

**Issue by manuco** [Martiusweb/asynctest#38]
`assertRaises()` works with and without a callable.

Without a callable, and as a context manager, `assertRaises()` works nicely. 

But with _something that can raises an exception but is not a bare callable_ such as `Task` or `Futures`, `assertRaises()` doesn't wait until the end of the _async callable like object_ to assert that no exception has been raised.

Wouldn't it be nice to write something like:
```python
import asyncio

# This is the function to be tested

@asyncio.coroutine
def background_work():
	yield from asyncio.sleep(0.1)
	raise RuntimeError("Plop")

# this is the test part

import asynctest

class MyTests(asynctest.TestCase):

	def setUp(self):
		self.t = asyncio.get_event_loop().create_task(background_work())

	@asyncio.coroutine
	def test_with_with(self):
		# This one is working
		with self.assertRaises(RuntimeError):
			yield from self.t

	@asyncio.coroutine
	def test_with_task(self):
		# Not this one
		yield from self.assertRaises(RuntimeError, self.t)

	def function_waiting_task(self):
		return (yield from self.t)

	@asyncio.coroutine
	def test_with_function(self):
		# Not this one
		yield from self.assertRaises(RuntimeError, self.function_waiting_task)

```

The point is the same with `assertRaisesRegex()`, `assertWarns()`, `assertWarnsRegex()`.

I'm not sure it is possible or easy to do, but if it is not, it should IMHO at least be documented.

**Comment by Martiusweb** [comment]
Hi, thanks for the report.

We can make assertRaises() and friends return a future if the callable is an awaitable, however, I don't like when a function is sometimes awaitable and sometimes not (ie: sometimes it's a plain function, sometimes it's a coroutine), as it's easy to forget the await/yield from.

However, it's easy to add new assertions like asynctest.TestCase.assertAsyncRaises(), which accepts awaitables.

I agree about the docs, it should be updated anyway.

**Comment by manuco** [comment]
The asynctest.TestCase.assertAsyncRaises() is indeed a very nice idea, which solve my precise case while being explicit.

**Comment by noam-fairfly** [comment]
It would be great to have this!
Is there any workaround you think about we could implement in the meantime?

**Comment by Martiusweb** [comment]
Hello, I implemented those methods, you can use the master branch until I release a new version of the package.
