### ISSUE TITLE
patch() returns a unittest.mock.MagicMock object

### ISSUE THREAD

**Issue by agronholm** [Martiusweb/asynctest#46]
The asynctest.mock.patch() function should return an async mock, but it doesn't:
```python
from asynctest.mock import patch

class Foo:
    async def bar(self): pass

with patch('__main__.Foo', autospec=True) as FooMock:
    print(type(FooMock))
```

**Comment by x0zzz** [comment]
Same for standalone coroutines:
```
from asyncio import get_event_loop
from asynctest import patch

async def f():
    print('f()')
   
async def test():
    with patch('__main__.f', autospec=True) as mock:
        await f()
        mock.assert_called_once_with(1)        

get_event_loop().run_until_complete(test())
```

Which leads to:
`TypeError: object MagicMock can't be used in 'await' expression`

@Martiusweb Any chances for a fix? Or at least a workaround enabling (auto)specing with a coroutine?

**Comment by Martiusweb** [comment]
I'll try to work on this bug (missing support of autospec) this week.

**Comment by Martiusweb** [comment]
Now that create_autospec() is overriden, I started to work on making it usable with @patch().

This is not yet merged, but feedback of the PR is welcome.
