### ISSUE TITLE
Instances of a mocked class don't return coroutine mocks for coroutine methods

### ISSUE THREAD

**Issue by agronholm** [Martiusweb/asynctest#47]
```python
from asynctest.mock import Mock

class Foo:
    async def bar(self): pass

FooMock = Mock(Foo)
print(type(FooMock.bar))
print(type(FooMock().bar))
```

**Comment by Martiusweb** [comment]
It's a case that is not supported because it seems that unittest can not detect that it's mocking a constructor, hence is not propagating the spec of the original mock:

    from unittest.mock import Mock

    class Foo:
     def bar(self): pass
    
    FooMock = Mock(Foo)   # <Mock spec='Foo' id='140305698455792'>
    foo = FooMock()       # <Mock name='mock()' id='140305698459208'>
    isinstance(foo, Foo)  # False
    foo = Mock(Foo())     # <Mock spec='Foo' id='140305695805000'>

To be honest, it's the kind of case I don't know what to do with, as fixing it means diverging from the behavior of unittest.

**Comment by Martiusweb** [comment]
This issue is solved by create_autospec(), which should be soon supported by asynctest (see #37), as the documentation of unittest.mock.create_autospec() says:
> If a class is used as a spec then the return value of the mock (the instance of the class) will have the same spec. You can use a class as the spec for an instance object by passing instance=True. The returned mock will only be callable if instances of the mock are callable.

https://docs.python.org/3/library/unittest.mock.html#unittest.mock.create_autospec
