### ISSUE TITLE
ClockedTestCase and sleep

### ISSUE THREAD

**Issue by dmzkrsk** [Martiusweb/asynctest#48]
I need to test some `async` functions with preserving some time order.
So I created mocks with `asyncio.sleep`.

The following code doesn't work. `sleep` blocks forever.

```python
import asyncio
import asynctest


class Sleep:
    def __init__(self, timeout, data):
        self.data = None
        self._data = data
        self.timeout = timeout

    async def do(self):
        await asyncio.sleep(self.timeout)
        self.data = self._data


class TestWithSleep(asynctest.ClockedTestCase):
    def setUp(self):
        self.sleep = Sleep(1, 'OK')

    def tearDown(self):
        self.sleep = None

    async def test_sleep(self):
        self.assertEqual(None, self.sleep.data)
        await self.advance(2)

        await self.sleep.do()
        self.assertEqual('OK', self.sleep.data)

```

This works (but can be slow):

```python

class TestWithSleep(asynctest.TestCase):
    def setUp(self):
        self.sleep = Sleep(1, 'OK')

    def tearDown(self):
        self.sleep = None

    async def test_sleep(self):
        self.assertEqual(None, self.sleep.data)
        await self.sleep.do()
        self.assertEqual('OK', self.sleep.data)
```

**Comment by Martiusweb** [comment]
Hi,

Your test can not work, because time only moves when you call advance():

    async def test_sleep(self):
        # self.loop.time() is 0
        await self.advance(2)
        # self.loop.time() is now 2

        # self.loop.time() is still 2
        # bellow you call asyncio.sleep(1), which means "awake me in time() + 1 = 3", which is never satisfied
        await self.sleep.do()  
        self.assertEqual('OK', self.sleep.data)


You must test you sleep function asynchronously:

    async def test_sleep(self):
        self.assertEqual(None, self.sleep.data)
        sleeping_tak = self.loop.create_task(self.sleep.do())
        self.assertFalse(sleeping_task.done())
        await self.advance(2)
        self.assertTrue(sleeping_task.done())
        self.assertEqual('OK', self.sleep.data)
