### ISSUE TITLE
Publish source distribution please

### ISSUE THREAD

**Issue by webknjaz** [Martiusweb/asynctest#50]
Hi @Martiusweb,

You publish only binary wheels, which leads to the situation where it's impossible to install it using distutils.

This happens with `pbr` tool (which is OpenStack's project being widely used in the wild):
https://travis-ci.org/webknjaz/asap-authentication-python/jobs/285562717#L489

Ref: https://github.com/pytest-dev/pytest-asyncio/issues/13#issuecomment-126959408

May I ask to to publish `sdist` as well?

P.S. Why not configure automatic deployment of distributions to PYPI straight from Travis CI? I could send you PR implementing this.

**Comment by Martiusweb** [comment]
Hi,
I uploaded the sources for the 0.10.0 release.

I'd gladly review a PR though :)

**Comment by webknjaz** [comment]
Thanks :)

**Comment by webknjaz** [comment]
@Martiusweb PR done.
