### ISSUE TITLE
Undefined method of a CoroutineMock instance returns MagicMock instead of CoroutineMock

### ISSUE THREAD

**Issue by rodcarroll** [Martiusweb/asynctest#52]
To reproduce:
```
x = CoroutineMock()
print(type(x.some_method))
```

In version 0.10.1:
`<class 'asynctest.mock.CoroutineMock'>`

In version 0.11.0:
`<class 'asynctest.mock.MagicMock'>`

This causes an unexpected breakage in existing tests.  Is there any way to get the old behavior back?

**Comment by Martiusweb** [comment]
Hi,

I'll look at why this behavior changed. However, I'm not sure you're using CoroutineMock the way I imagined: CoroutineMock is made to mock a coroutine function, but it seems that you're using it to mock an object.

If you want to mock, say:

    class Foo:
       async def my_coro(): pass

you should do:

     foo_mock = asynctest.mock.MagicMock(Foo)

which will detect that my_coro() must be mocked as a CoroutineMock.

If you don't want to specify "Foo" as the spec, you will need something like:

    x.some_method.is_coroutine = True

I never intended CoroutineMock to be a way to mock an object for which all attributes are coroutine functions, but that doesn't mean it's not a good idea. I'll think about it.

**Comment by rodcarroll** [comment]
You're right - I had been using CoroutineMock as an all-around replacement for MagicMock with an async context, including for objects with async methods, but the naming and your suggestions make sense.  It looks as though I've been relying on undefined behavior.

**Comment by jacobtomlinson** [comment]
I'm using `CoroutineMock` to patch out a coroutine, awaiting it, then asserting that it has been called. Here's an [example](https://github.com/opsdroid/opsdroid/blob/master/tests/test_memory.py#L25).

This has broken since 0.11.0.

**Comment by Martiusweb** [comment]
You're doing the same thing: you're testing the object which has the attributes put() and get() which are the coroutines.

I'm a bit concerned because it's seems to be a quite common practice but I'm not sure it's a good one.
I'll try to revert to the old behavior but I feel like I should create a proper API for this case (children members of a mock being CoroutineMock by default) and warn about using attributes of a CoroutineMock.

Maybe something like ``Mock(attributes_are_coroutines=True)`` or something similar.

**Comment by jacobtomlinson** [comment]
If you don't think it's a good practice I'm totally open to doing it
differently. I could just do with some pointers in the right direction.

The thing I've struggled with most in testing asyncio code is the lack of
docs. More examples of best practice would be really useful.

**Comment by Martiusweb** [comment]
In your case, I would have written your example this way:

        memory = self.setup()
        memory.databases = [mock.MagicMock()]
        memory.databases[0].get = CoroutineMock()
        memory.databases[0].put = CoroutineMock()
        data = "Hello world!"

but a convenient way to specify that the attributes of the MagicMock should all be coroutines mocks can be useful.

You're right about the documentation and examples, I'll try to work on this too.

**Comment by jacobtomlinson** [comment]
Awesome thanks 👍
