### ISSUE TITLE
Add long description to PYPI

### ISSUE THREAD

**Issue by webknjaz** [Martiusweb/asynctest#53]
See: https://pypi.org/project/asynctest/0.11.0/

@Martiusweb if you're okay with sticking to `setuptools>=30.3.0`, I'd send a PR using nice feature of automatic reading of README into `long_description` using declarative `setup.cfg`.

**Comment by Martiusweb** [comment]
Hi, would it block someone using an older version of setuptools installing asynctest?
If not, I'll welcome the PR 👍

**Comment by webknjaz** [comment]
@Martiusweb it depends: older version will just omit reading/parsing `setup.cfg`.
We could add `__requires__ = ('setuptools>=30.3.0', )` and then it will raise an exception asking user to install required version. But otherwise, it shouldn't affect users, unless we drop stuff from `setup.py`.
Oh.. and we'll need to upgrade setuptools in CI as well, before building dist, but that's easy.

Honestly, newer versions of setuptools bring features and improvements, so I feel good when promoting upgrades :)
For example, a while ago (`>=36.3`) I've added ability to concatenate more than one file in `setup.cfg` (if one needs to include their contents to long description), which will not be available to users unless they upgrade. This helps eliminate coding in `setup.py` (now lots of people just do lots of magic there, which is unfortunate)

So, it's declarative `setup.cfg`
```ini
[metadata]
long_description = file: README.rst
```

v.s. 

coding the `setup.py`
```python
from setuptools import setup
...
with open('README.rst') as readme:
    LONG_DESC = readme.read()

__name__ == '__main__' and setup(
    ...,
    long_description=LONG_DESC,
    ...,
)
```

**Comment by Martiusweb** [comment]
Fwiw, I usually check what is provided by the latest LTS of ubuntu. The version of setuptools that it distributes is 20.7.

Since this feature is only useful when doing a release on pypi, I think we should not force users to update their dependencies if they want to install asynctest.

Let's force the version in the CI and rely on features of setuptools that users can safely ignore if they run with an older version.

**Comment by webknjaz** [comment]
Ref #54

**Comment by Martiusweb** [comment]
I rebased your commits and updated the setup.py script:
https://github.com/Martiusweb/asynctest/commit/341d24c51c000f5103b6a6a45dbea01291940663

What do you think of it?

**Comment by webknjaz** [comment]
You could push in my repo instead of pushing additional branch here: this would go to the PR page and would be easier to comment on :)

**Comment by webknjaz** [comment]
I've added a few comments there

**Comment by Martiusweb** [comment]
I merged you changes with mine.
Thanks :)
