### ISSUE TITLE
Question about setUp/tearDown vs. setup_method/teardown_method

### ISSUE THREAD

**Issue by kevinkjt2000** [Martiusweb/asynctest#58]
Following xunit-style documentation that the normal pytest.TestCase is capable of https://docs.pytest.org/en/latest/xunit_setup.html
I tried using setup_method and teardown_method instead of setUp and tearDown, but using the former caused one of my tests to fail.  Are these handled differently somehow by asynctest.TestCase?

If you would like to reproduce the failing tests that I am referring to:
https://github.com/kevinkjt2000/discord-minecraft-server-status/blob/4952acf35af552941315c5c02a98ec9f1b3badfe/test/test_main.py#L31
clone, `pip install -e.[dev]`, change the setUp and tearDown from that permalink, and run pytest.

P.S.: Thanks a ton for supporting async MagicMocks!  That enabled me to even write these tests in the first place! :)

**Comment by Martiusweb** [comment]
I'm not sure I understand what you're trying to do.
To answer the question:
> Are these handled differently somehow by asynctest.TestCase?
asynctest is able to detect that a setUp() or tearDown() method is a coroutine and will run before/after the test using the loop created for the test.

asynctest.TestCase inherits from unittest.TestCase and is not directly related to pytest (which is an independent testing library). unittest and asynctest don't support these methods (setup_method, teardown_method).

I see in the code you linked that a @asyncio.coroutine is missing for the tearDown() method:
https://github.com/kevinkjt2000/discord-minecraft-server-status/blob/4952acf35af552941315c5c02a98ec9f1b3badfe/test/test_main.py#L40

In this case, asynctest can't detect that your method is a coroutine and will not run it: it will only create an instance of a generator.

**Comment by kevinkjt2000** [comment]
Is my `tearDown` a coroutine though?  I used `yield from` because I thought I was being synchronous on this.  Hmmmm... Thanks for pointing this out.  I just now went back and tried adding a print statement that did not show up.  I have switched it to `async` and using `await` instead of `yield from`.

When I use setup_method and teardown_method with unittest.TestCase, they do work.  Hmmm... now that both my setup_method and teardown_method are marked with `async`, I can see a nice set of stacktraces:
```
test/test_main.py::TestBot::test__status_command_when_the_server_does_not_respond
  /home/kevin/repos/discord-minecraft-server-status/venv/lib/python3.6/site-packages/_pytest/unittest.py:77: RuntimeWarning: coroutine 'TestBot.setup_method' was never awaited
    self._testcase.setup_method(self._obj)
  /home/kevin/repos/discord-minecraft-server-status/venv/lib/python3.6/site-packages/_pytest/unittest.py:96: RuntimeWarning: coroutine 'TestBot.teardown_method' was never awaited
    self._testcase.teardown_method(self._obj)

test/test_main.py::TestBot::test__tells_the_user_when_the_ip_is_bad
  /home/kevin/repos/discord-minecraft-server-status/venv/lib/python3.6/site-packages/_pytest/unittest.py:77: RuntimeWarning: coroutine 'TestBot.setup_method' was never awaited
    self._testcase.setup_method(self._obj)
  /home/kevin/repos/discord-minecraft-server-status/venv/lib/python3.6/site-packages/_pytest/unittest.py:96: RuntimeWarning: coroutine 'TestBot.teardown_method' was never awaited
    self._testcase.teardown_method(self._obj)```

And I think you are on to something about pytest being the one that is responsible here.  I guess I will stick with setUp and tearDown for now.  Even though my OCD is a little triggered by the rest of the functions in the class being of the form test_spam_eggs.

Thanks for taking the time to answer this!
