### ISSUE TITLE
The unused check loop method should be disabled by default for non-coroutine methods

### ISSUE THREAD

**Issue by Kentzo** [Martiusweb/asynctest#63]
Normal methods are likely to be used for non-asyncio tests.

**Comment by Martiusweb** [comment]
This check is here to ensure that the test is actually a coroutine when it should:
* an old-style coroutine missing the @asyncio.coroutine decorator will not run on the loop, the test will never fail (it only creates an instance of the generator),
* when all assertions are running in async code, failure can be hidden, like in this example:

      def test_start_my_app(self):
         @asyncio.coroutine
         def verify_things():
              self.assertTrue(False)
         # start_my_app can be buggy and never schedule verify_things, but the test will pass
         start_my_app(verify_things)

I assume that someone using asynctest will run asynchronous stuff in its test. If not, the @lenient decorator is here to disable all checks.

**Comment by Kentzo** [comment]
@Martiusweb I do not think it makes sense to complicate testing of old-style coroutines when 3.7 is about to be released and `async` / `await` syntax is pretty standard.

It's true it can be configured but if asynctest strives to be a drop in replacement non-async methods should work out of the box.

**Comment by Martiusweb** [comment]
I agree with your last comment. We can deactivate the "unused loop" check by default.
