### ISSUE TITLE
Full control over awaitable mock

### ISSUE THREAD

**Issue by Kentzo** [Martiusweb/asynctest#64]
When writing asyncio tests it is to control when and what awaitable mock should return.

Here is an example to give an idea:

```python
class MagicCoro(unittest.mock.Mock):
    """
    >>> m = unittest.mock.MagicMock()
    >>> m.coro = MagicCoro(return_value=42)
    >>> assert await m.coro() == 42
    >>> assert m.exit.is_set()
    """
    def __init__(self, run_event=None, return_value=None):
        async def coro(*args, **kwargs):
            self.enter.set()

            if self.run:
                await self.run.wait()

            self.exit.set()

            return self.value

        super().__init__(wraps=coro)

        self.enter = asyncio.Event()
        self.run = run_event
        self.exit = asyncio.Event()
        self.value = return_value

    def _get_child_mock(self, **kw):
        return unittest.mock.MagicMock(**kw)
```

This allows to:
- provide a return value
- provide an event to wait for allowing user to control completion order
- assert whether coroutine was entered or exited

**Comment by Martiusweb** [comment]
This is something that can be added to the helpers module:
http://asynctest.readthedocs.io/en/latest/asynctest.helpers.html

**Comment by Kentzo** [comment]
@Martiusweb I was thinking about adding an extra attribute to `CoroutineMock` to "await" its call.

**Comment by nopcall** [comment]
https://docs.python.org/3/reference/datamodel.html?#awaitable-objects

i think you forgot __await__ function.
