### ISSUE TITLE
Patching target object with new argument results in error

### ISSUE THREAD

**Issue by jeryini** [Martiusweb/asynctest#75]
Hello!

I'm trying to patch these three objects like that:
```
@asynctest.patch('foo.bar.method_1', new=asynctest.CoroutineMock)
@asynctest.patch('foo.bar.method_2', new=asynctest.CoroutineMock)
@asynctest.patch('foo.bar.method_3')
async def test_foo_bar(self, mock_method_3, method_2, method_1):
```
So I'm using the `new` argument because the library doesn't properly identify the patched object (`async def statement`) as a coroutine. When running the tests I get the following error:
```
args = (<tests.unit_tests.test_app.test_foo_bar.TestRunFooBar testMethod=test_foo_bar>, <CoroutineMock name='method_3' id='140075174886144'>)
keywargs = {}
extra_args = [<CoroutineMock name='method_3' id='140075174886144'>]
patchers_to_exit = [<asynctest.mock._patch object at 0x7f65cbb5a080>]
patch_dict_with_limited_scope = []
exc_info = (<class 'TypeError'>, TypeError("test_foo_bar() missing 2 required positional arguments: 'method_2' and 'method_1'",), <traceback object at 0x7f65cb0a58c8>)
patching = <asynctest.mock._patch object at 0x7f65cbb5a080>
arg = <class 'asynctest.mock.CoroutineMock'>
```

**Comment by Martiusweb** [comment]
Hello,
@patch should be able to detect the the patched object is a coroutine, this is unit tested here:
https://github.com/Martiusweb/asynctest/blob/master/test/test_mock.py#L382

Can you tell which version of asynctest you're using and provide an example of code showing the bug so we can reproduce it?

In particular, what are ``foo.bar.method_1`` and ``foo.bar.method_2``?

Cheers

**Comment by jeryini** [comment]
Hello @Martiusweb! First of all thank you for quick response. So I'm using version *0.11.1*. Looking at your test, you are only testing if a method decorated with `@asyncio.coroutine` is patched using `CoroutineMock`, but also not method implemented using `async def` statement (as defined in [official docs](https://docs.python.org/3/library/asyncio-task.html#coroutines)).

The methods `foo.bar.method_1` and `foo.bar.method_2` are both coroutines that are implemented using the `async def` statement:
```
@staticmethod
async def method_2(ids: List[uuid.UUID]=None, exclude_ids: List[uuid.UUID]=None, db: Connection=None) -> List["some_objects"]:

async def method_1(some_objects: List["some_objects"], conn: Connection, ran_at: datetime):
```

**Comment by Martiusweb** [comment]
I tested with:

    import asyncio
    import asynctest

    class Foo:
        async def plop(self):
            pass


    @asynctest.patch('__main__.Foo.plop')
    async def test_foo_bar(mock):
        print(Foo.plop)


    asyncio.get_event_loop().run_until_complete(test_foo_bar())

and when I run this:

    $ python plop.py 
    <CoroutineMock name='plop' id='139763259136432'>

the patched method is a CoroutineMock.

Btw, there's the same test for async-defined coroutine:
https://github.com/Martiusweb/asynctest/blob/master/test/test_mock.py#L405

**Comment by jeryini** [comment]
Interesting, because if I don't use the `new=asynctest.CoroutineMock` and print the type of the mocked object, it says `<class 'asynctest.mock.MagicMock'>`. The test of course then fails, as I'm mocking the return value of `method_2` as `method_2.return_value = []` and because it's a `MagicMock` not a `CoroutineMock`, I get the following error:
```TypeError: object list can't be used in 'await' expression```

**Comment by Martiusweb** [comment]
Unfortunatly, if I can't reproduce the bug, there's nothing I can do to help you.
Can you provide a minimal test case which shows the bug that I can run to test?

**Comment by jeryini** [comment]
Hmm, can you maybe then explain, why if I change in your example to the following:
```

**Comment by jeryini** [comment]
Whoops, just checked the implementation in `asynctest` and saw that you actually need to provide `new_callable=asynctest.CoroutineMock`, not `new`.

**Comment by Martiusweb** [comment]
If you use the new argument, the mock is not passed as a parameter of the patched function, thus, you need to do something like:

    @asynctest.patch('__main__.Foo.plop', new=...)
    async def test_foo_bar():  # no mock arg
        print(Foo.plop)

This is the behavior of unittest.mock.patch: https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch

> If new is omitted, then the target is replaced with a MagicMock. If patch() is used as a decorator and new is omitted, the created mock is passed in as an extra argument to the decorated function. If patch() is used as a context manager the created mock is returned by the context manager.

**Comment by jeryini** [comment]
Hello again, I've managed to fix my tests now. What confused me was this [this part of the docs|http://asynctest.readthedocs.io/en/latest/asynctest.mock.html#asynctest.patch]:

> If new isn’t provided, the default is a CoroutineMock if the patched object is a coroutine, or a MagicMock object.

I thought that `new` argument controls the type of the mock, not the `new_callable`. Is this perhaps still old documentation?

**Comment by Martiusweb** [comment]
``new`` allows to specify which object will replace the original patched object. if this parameter is not provided, the default behavior is to use a new instance of CoroutineMock or MagicMock (depending of whether the target of the patch is a coroutine function or not).

``new_callable`` allows to specify a callable which returns the object that will replace the target of the patch. This one can be used to specify the type of the object that will replace the target, but it can be any kind of callable an can return something else than a mock.

I try to avoid repeating the documentation of unittest in asynctest' documentation, but that's true that this is far from obvious. I'll rework the doc a bit.

**Comment by jeryini** [comment]
Great, thank you very much for explanation. I'm closing this issue now as I've resolved it.
