### ISSUE TITLE
Add the examples section to the docs

### ISSUE THREAD

**Issue by Kentzo** [Martiusweb/asynctest#77]
`Mock` objects can be confusing. The examples section should cover common cases to make user familiar with common tasks.

**Comment by Martiusweb** [comment]
I'm writing a tutorial which should cover most of  the common use cases. It's in the documentation branch. 

I'd be more than happy to receive comments and feedbacks. Especially, tell me if you think some features deserve to be explained in detail.

**Comment by Martiusweb** [comment]
A first "complete" version of the tutorial is available in the documentation branch. I'll probably merge it tomorrow, so it will be available for anyone to review.

**Comment by Martiusweb** [comment]
I will close the issue now that the tutorial has been merged. Of course, it can be improved. For instance, it can be interesting to show how to mock the most commons libraries (aiohttp, etc).
