### ISSUE TITLE
Patch the Class object

### ISSUE THREAD

**Issue by Olegt0rr** [Martiusweb/asynctest#88]
Can't patch Class object, only methods

Working case, but too many decorator lines...
```
class TestGamePrepare(TestCase):
    chat_id = -12345667890
    admin_id = 987654321

    async def setUp(self):
        self.game = await get_game(self.chat_id)

    @patch('game.Game.delete_messages', pass_func)
    async def tearDown(self):
        await self.game.cancel()

    @patch('game.Game.say', pass_func)
    @patch('game.Game.unmute', pass_func)
    @patch('game.Game.read_game_settings', pass_func)
    @patch('game.Game.delete_messages', pass_func)
    async def test_game_prepare(self):
        """ Good prepare case """
        await self.game.prepare_game(self.admin_id)
        self.assertEqual(self.game.mode, GameModes.REGISTRATION)
```

I try to patch Class at all, but it's not working:
```
    @patch('game.Game', NewGame)
    async def test_game_prepare(self):
        """ Good prepare case """
        await self.game.prepare_game(self.admin_id)
        self.assertEqual(self.game.mode, GameModes.REGISTRATION)
```

What's wrong?

**Comment by Martiusweb** [comment]
I'm not sure I understand your problem precisely. What are you trying to do or what is not working?
Can you provide code that we can run to reproduce your problem, and give more details about the game.Game class?

**Comment by Olegt0rr** [comment]
I Just trying to patch any class to another class (i.e. it child)

game.py file:
```
class Game:
    async def action(self):
        return 'Original action'
    
    async def another_action(self):
        return 'Another action'
```


test_game.py file:
```
class NewGame(Game):
     async def action(self):
        return 'Patched action'

class TestGame(TestCase):
    async def setUp(self):
        self.game = Game()

    @patch('game.Game', NewGame)
    async def test_game_prepare(self):
        result = await self.game.action()
        self.assertEqual(result, 'Patched action')
```

**Comment by Martiusweb** [comment]
Sorry for the very late reply, I missed the notification somehow.

The patch is only effective in the scope of the method it decorates, this means that when you call

    self.game = Game()

in the setUp, the patch is not doing anything yet.

You can run the patch in the setUp though:

    async def setUp(self):
         with asynctest.patch('game.Game', NewGame):
              self.game = Game()

should work.
