### ISSUE TITLE
Error in 'async with' statement when mocking coroutine that returns MagicMock

### ISSUE THREAD

**Issue by jamezmoran** [Martiusweb/asynctest#94]
import pytest
    import asyncio
    from asynctest import MagicMock, CoroutineMock

    class TestClass(object):
        @pytest.mark.asyncio
        async def test_get_queue_url(self):
            test_client = MagicMock()
            test_session = MagicMock()
            expected = "testvalue"

            test_client.get_test = CoroutineMock(side_effect=[expected])
            test_session.create_client = CoroutineMock(side_effect=[test_client])
            async with test_session.create_client("something") as client:
                print("hello")

For some reason, this generates the following error:

	self = <test_Distributor.TestClass object at 0x00000242FDA174A8>

		@pytest.mark.asyncio
		async def test_get_queue_url(self):
			test_client = MagicMock()
			test_session = MagicMock()
			expected = "testvalue"

			test_client.get_test = CoroutineMock(side_effect=[expected])
			test_session.create_client = CoroutineMock(side_effect=[test_client])
	>       async with test_session.create_client("something") as client:
	E       AttributeError: __aexit__

Is this expected? I would've thought that the coroutine gets called and returns the MagicMock, which should be able to be used in the `async with` statement. Unless I'm doing something wrong, maybe someone can point me in the right direction.

Thanks!

**Comment by Kentzo** [comment]
`test_session.create_client` is a coroutine mock that acts as a [coroutine function](https://docs.python.org/3/glossary.html#term-coroutine-function). A coroutine function returns an [coroutine object](https://docs.python.org/3/glossary.html#term-coroutine). In other words it will not return `test_client` unless you await it: `async with (await test_session.create_client("something")) as client`.

Alternatively, change type of `test_session.create_client` to `asynctest.MagicMock`.

**Comment by jamezmoran** [comment]
Thanks for the fast response. I changed it to a MagicMock and that resolved that error, although I've got another immediately afterwards that I can't seem to figure out either:

    @pytest.mark.asyncio
    async def test_get_queue_url(self):
        test_client = MagicMock()
        test_session = MagicMock()
        expected = "expectedurl"
        queue_name = "queuename"

        test_client.get_test = CoroutineMock(side_effect=[expected])
        test_session.create_client = MagicMock(side_effect=[test_client])
        async with test_session.create_client() as client:
    >       print(await client.get_test())
    E   TypeError: object MagicMock can't be used in 'await' expression

Printing out the type of `client` gives me this:

    <MagicMock name='mock.__aenter__()' id='2225310076768'/>

Printing out 'test_client.get_test' directly confirms it's a CoroutineMock, it just doesn't seem to work within the async context. Apologies for asking so many questions, it's just not too intuitive to me what exactly's going on.

**Comment by jamezmoran** [comment]
@Kentzo that didn't seem to work, I still receive the same error:

        test_session.create_client.__aenter__.get_test = CoroutineMock(side_effect=[expected])
        async with test_session.create_client() as client:
    >       print(await client.get_test())
    E       TypeError: object MagicMock can't be used in 'await' expression

**Comment by Martiusweb** [comment]
@Kentzo is correct but missing a small thing:

__aenter__ is called on the result of create_client(), not create_client itself, you need to do something like:
test_session.create_client().__aenter__.get_test = CoroutineMock(side_effect=[expected])

**Comment by jamezmoran** [comment]
@Martiusweb I get same error as above with that modification:

        test_session.create_client.aenter.get_test = CoroutineMock(side_effect=[expected])
        async with test_session.create_client() as client:
            print(client)
    >       print(await client.get_test())
    E       TypeError: object MagicMock can't be used in 'await' expression

**Comment by Martiusweb** [comment]
I think you misunderstood my comment because of the bad formatting.

When python executes

    with A as B:
        pass

the interpreter calls A.__aenter__ (a coroutine) and the result of this call is assigned to the symbol B.
In you case A is test_session.create_client(), which means that the method __aenter__ is called on the object returned by the call to test_session.create_client, not on the create_client mock itself.

this means that you need to do something like:

    mock_client = MagicMock()
    mock_client.get_test = CoroutineMock(return_value=expected)

    context_manager = MagicMock()
    context_manager.__aenter__.return_value = mock_client

    mock_session = MagicMock()
    mock_session.create_client.return_value = context_manager

**Comment by Martiusweb** [comment]
again, I dont mean aenter in bold case but ``__aenter__``.

**Comment by jamezmoran** [comment]
Thanks a lot @Martiusweb and @Kentzo, these explanations were very helpful for me! Closing as my issue is now resolved.
